development:
  adapter: postgresql
  encoding: utf8
  database: open_api_search_development
  username: adminbot
  host: localhost
  pool: 30
  timeout: 15000

test:
  adapter: postgresql
  encoding: utf8
  database: open_api_search_test
  username: adminbot
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: open_api_search_production
